openapi: 3.0.1
info:
  contact: {}
servers:
- url: /
paths:
  /books:
    get:
      tags:
      - books
      summary: Get all books
      description: Retrieve a list of all books
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/models.Book'
                x-content-type: application/json
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.ErrorResponse'
    post:
      tags:
      - books
      summary: Create a new book
      description: Create a new book with the provided details
      requestBody:
        description: Book object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.Book'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.Book'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.ErrorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.ErrorResponse'
      x-codegen-request-body-name: book
  /books/{id}:
    get:
      tags:
      - books
      summary: Get a book by ID
      description: Retrieve a book by its ID
      parameters:
      - name: id
        in: path
        description: Book ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.Book'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.ErrorResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.ErrorResponse'
    put:
      tags:
      - books
      summary: Update a book
      description: Update a book with the provided details
      parameters:
      - name: id
        in: path
        description: Book ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        description: Book object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.Book'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.Book'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.ErrorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.ErrorResponse'
      x-codegen-request-body-name: book
    delete:
      tags:
      - books
      summary: Delete a book
      description: Delete a book by its ID
      parameters:
      - name: id
        in: path
        description: Book ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: No Content
          content: {}
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/models.ErrorResponse'
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/models.ErrorResponse'
components:
  schemas:
    models.Book:
      type: object
      properties:
        author:
          type: string
        created_at:
          type: string
        id:
          type: integer
        published_at:
          type: string
        title:
          type: string
        updated_at:
          type: string
      example:
        updated_at: updated_at
        author: author
        created_at: created_at
        id: 0
        published_at: published_at
        title: title
    models.ErrorResponse:
      type: object
      properties:
        error:
          type: string
x-original-swagger-version: "2.0"
