/*
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModelsBook struct {
	Author string `json:"author,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Id int32 `json:"id,omitempty"`
	PublishedAt string `json:"published_at,omitempty"`
	Title string `json:"title,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
